<div class="std-popup">
    <div class="header">
        <?= $header ?>
        <?php
        if($headerBtns == 'tableEdit') {
            $html = 
                '<div class="sidebar">'.
                    '<span class="btn item-save" title="Сохранить"><i class="fal fa-cloud-upload"></i></span> '.
                    '<span class="btn item-del" title="Удалить"><i class="fal fa-trash-alt"></i></span> '.
                    '<span class="btn close" data-fancybox-close><i class="fal fa-times"></i></span>'.
                '</div>';
        } else {
            $html = 
                '<div class="sidebar">'.
                    '<span class="btn close" data-fancybox-close><i class="fal fa-times"></i></span>'.
                '</div>';
        }
        echo $html;
        ?>
    </div>
    <div class="body">
        <?= $this->content; ?>
    </div>
</div>


