<?php
echo $this->tags([
    ['row', 'style' => ['padding-top' => '30px'], 'tags' => [
        ['td', 'align' => 'left', 'text' => $proposal
            /*['p', 'text' => 'Контакты: '],
            ['p', 'text' => 'Вопрос: ' . $comment->get('question')],
            ['p', 'text' => 'Язык: ' . $comment->get('lang'), 'style' => ['padding-bottom' => '30px']],
            ['btn', 'href' => 'https://' . $_SERVER['HTTP_HOST'] . '/admin/comments/comments/edit/?id=' . $comment->id() . '/', 'text' => 'Ответить'],*/
        ],
    ]],
]);