<div class="popup-order-documents std-form">
    <?php
    $factory = $this->formFactory()->setForm($form);

    echo $factory->structure([
        ['order_id'],
        [
            ['width' => 100, 'element' => 'client_id'],
            ['width' => 100, 'element' => 'document_id'],
        ]
    ]);
    ?>
    <div class="btn download">Скачать в Word</div>

    <script>
        $(function () {
            var form = $('.popup-order-documents');

            $('.download', form).on('click', function () {
                var data = {
                    order_id: $('[name="order_id"]', form).val(),
                    client_id: $('[name="client_id"]', form).val(),
                    document_id: $('[name="document_id"]', form).val(),
                };

                if(data.client_id === '' || !data.document_id === '') {
                    alert('Выберите контрагента и шаблон');
                    return;
                }

                $url = new Url();
                $url.setPath('/documents/get-filled/');
                $url.setParams(data);

                window.open($url.getUrl(),'_blank');
            });
        });
    </script>

    <style>
        .popup-order-documents {
            min-width: 525px;
        }
    </style>
</div>