<table width="100%" bgcolor="#f0f0f0" cellpadding="0" cellspacing="0" border="0" id="backgroundTable" st-sortable="menu">
    <tbody>
    <tr>
        <td>
            <table width="630" bgcolor="#ffffff" cellpadding="0" cellspacing="0" border="0" align="center" class="devicewidth">
                <tbody>
                <tr>
                    <td width="100%" style="padding: 20px">
                        <?php echo $text ?>
                    </td>
                </tr>
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>